[package]
name = "rs-madsim-net-simple"
version = "0.1.0"
edition = "2024"

[dependencies]
madsim = "0.2.34"
rand = "0.10.1"
tokio = { version = "0.2.25", package = "madsim-tokio", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(madsim)'] }   
