[package]
name = "rs-nucleo-f446re-blinky-rate-button-controlled"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
critical-section = "1.2.0"
fugit = "0.3.9"
panic-halt = "1.0.0"
stm32f4xx-hal = { version = "0.23.0", features = ["stm32f446"] }
